name: VS Code Extension

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        working-directory: apps/vscode-extension
        run: npm install

      - name: Compile TypeScript
        working-directory: apps/vscode-extension
        run: npm run compile

      - name: Package Extension
        working-directory: apps/vscode-extension
        run: npm run package
